import { type NextPage } from "next";
import Head from "next/head";
import Layout from "./components/Layout";

import { api } from "~/utils/api";


const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Isaiah Simon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Your content goes here */}
      </Layout>
    </>
  );
};

export default Home;
